feat(oh-my-linux): add CLI!

diff --git a/oh-my-linux b/oh-my-linux
--- a/oh-my-linux
+++ b/oh-my-linux
@@ -26,8 +26,9 @@
 # LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
-
-# set -e 
+#
+# This cil script was generated by bashly (https://github.com/DannyBen/bashly)
+# 
 
 # Imports:
 SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
@@ -35,9 +36,12 @@ SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
 . $SCRIPTPATH/lib/sysinfo.sh --source-only
 . $SCRIPTPATH/lib/tools.sh
 
+
 # Build variables:
 BUILD_DIRECTORY=$SCRIPTPATH/build/
 BUILD_SCRIPT=$BUILD_DIRECTORY/install.sh
+SCRIPTS_DIRECTORY=$SCRIPTPATH/scripts
+
 header_sources=(
     $SCRIPTPATH/lib/logs.sh
     $SCRIPTPATH/lib/sysinfo.sh
@@ -58,7 +62,7 @@ selected_scripts=();
 
 _checklist=;
 
-# Functions:
+# ==== Functions =====
 BFS() {
     # Breadth-First Search algorithm
     # this function adds in 'stack' all dependencies for correct script
@@ -139,8 +143,13 @@ parse_config_file(){
     log_debug "depends_on [$2] = ${metadata[depends_on]}";
 }
 
-detect_scripts_directories() {     
-    for f in $SCRIPTPATH/scripts/*; do
+detect_scripts_directories() {
+    scripts_directory_array=();
+    scripts_files=();
+    scripts_names=();
+    scripts_description=();
+    
+    for f in $SCRIPTS_DIRECTORY/*; do
         if [ -d "$f" ]; then
             # $f is a directory
             log_info "info $f"
@@ -188,9 +197,42 @@ parse_checklist_output() {
     done
 }
 
+remove_script_dir() {
+  local _name=$1;
+  local _path=$SCRIPTS_DIRECTORY/$_name
+  log_warning "Remove $_path"
+  rm -rf $_path/
+}
+
+append_new_script_dir() {
+  local _name=$1;
+  local _deps=$2;
+  local _path=$SCRIPTS_DIRECTORY/$_name
+  
+  log_info "_path = $_path"
+  if [ -d "$_path" ]; then
+      log_success "$_path already exists!"
+      return
+  fi
+
+  mkdir -p $_path/
+
+  echo "# $_name" > $_path/install.sh
+  echo "" >> $_path/install.sh 
+
+  echo "[metadata]" > $_path/info.cfg
+  echo "name=$_name" >> $_path/info.cfg
+  echo "description=..." >> $_path/info.cfg
+  echo "file=install.sh" >> $_path/info.cfg
+
+  if [ $_deps ]; then
+    echo "depends_on=$_deps" >> $_path/info.cfg    
+  fi
+}
+
 initial_build_directory() {
     if [ -d "$BUILD_DIRECTORY" ]; then
-        log_warning "Remove $BUILD_DIRECTORY!"
+        log_warning "Remove build directory: $BUILD_DIRECTORY"
         rm -rf $BUILD_DIRECTORY;
     fi
 
@@ -213,7 +255,7 @@ build_script() {
 
     for name in "${stack[@]}"; do # 
         log_info "Add script = $name"
-        local script_file=$SCRIPTPATH/scripts/$name/${scripts_files[$name]}
+        local script_file=$SCRIPTS_DIRECTORY/$name/${scripts_files[$name]}
         log_info "script_file = $script_file"
 
         append_script_file_to_build "$script_file";
@@ -232,7 +274,7 @@ build_script() {
 ask_start_script() {
     local dio_name="Statr script?"
     local dio_discription="Statr script?"
-    if (whiptail --title "$dio_name" --yesno "$dio_discription" 8 78); then
+    if (whiptail --title "$dio_name" --yesno "$dio_discription" 8 78) || []; then
         log_info "Start script!"
         bash $BUILD_SCRIPT;
     else
@@ -244,56 +286,349 @@ ask_start_script() {
     fi
 }
 
+select_scripts() {
+    if [[ ${args[select]} ]]; then
+      selected_scripts=(${args[select]})
+    else
+      OUTPUT=$(whiptail --checklist "Please pick one" 10 60 4 $_checklist  3>&2 2>&1 1>&3 )
+      parse_checklist_output $OUTPUT;
+    fi
 
-main() {
-    print_logo; # TODO: add CLI flag
-
-    detect_scripts_directories;
-    # OUTPUT=$(whiptail --checklist "Please pick one" 10 60 4 $_checklist  3>&2 2>&1 1>&3 )
-    
-    # checklist_out=$()
-    # log_success "OUTPUT = $OUTPUT"
-    # parse_checklist_output $OUTPUT;
-
-    selected_scripts=(test_a vlc)
-    log_success "selected_scripts = ${selected_scripts[@]}"
-
-    # TODO: добавить топологическую сортировку selected_scripts!!!
-    
-
-    topological_sort; 
-    build_script;
-    # log_success "OUTPUT = ${OUTPUT[1]}" 
-    # Получаем список выбранных
-
-    # из списка выбранных делаем спикок зависимостей
-
-    # Из списка зависимостей составляем с помощью топологической сортировки
-
-    # собираем билд
-
-
-     
-    # whiptail --checklist "Please pick one" 10 60 4 one one off two two off\
-    #     three three off four four off  five five off
-    
-    # ask_start_script;
-
-    # update_graph;
-
-    log_debug "scripts_directory_array = ${scripts_directory_array[@]}"
-
-    log_debug "depends_on = "
-    for K in "${!depends_on[@]}"; do echo $K --- ${depends_on[$K]}; done
-
-    
-    log_debug "visited = "
-    for K in "${!visited[@]}"; do echo $K --- ${visited[$K]}; done
-
-    log_debug "stack = "
-    for K in "${!stack[@]}"; do echo $K --- ${stack[$K]}; done
+  log_info "selected_scripts = ${selected_scripts[@]}"
 }
 
+# ====== CLI =======
+# :command.version_command
+version_command() {
+  echo "$version"
+}
+
+# :command.usage
+oh_my_linux_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "oh-my-linux - Oh My Linux\n"
+    echo 
+  else
+    printf "oh-my-linux - Oh My Linux\n"
+    echo 
+  fi
+
+  printf "Usage:\n"
+  printf "  oh-my-linux [command]\n"
+  printf "  oh-my-linux [command] --help | -h\n"
+  printf "  oh-my-linux --version | -v\n"
+  echo
+  # :command.usage_commands
+  printf "Commands:\n"
+  echo "  build   Build script"
+  echo
+
+  if [[ -n $long_usage ]]; then
+    printf "Options:\n"
+    # :command.usage_fixed_flags
+    echo "  --help, -h"
+    printf "    Show this help\n"
+    echo
+    echo "  --version, -v"
+    printf "    Show version number\n"
+    echo
+
+    # :command.usage_environment_variables
+    printf "Environment Variables:\n"
+    
+    # :environment_variable.usage
+    echo "  DEBUG"
+    printf "    Enable debug mode\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+oh_my_linux_build_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "oh-my-linux build - Build script\n"
+    echo 
+  else
+    printf "oh-my-linux build - Build script\n"
+    echo 
+  fi
+
+  printf "Shortcut: b\n"
+  echo
+
+  printf "Usage:\n"
+  printf "  oh-my-linux build [SELECT] [options]\n"
+  printf "  oh-my-linux build --help | -h\n"
+  echo
+
+  if [[ -n $long_usage ]]; then
+    printf "Options:\n"
+    # :command.usage_fixed_flags
+    echo "  --help, -h"
+    printf "    Show this help\n"
+    echo
+    # :command.usage_flags
+    # :flag.usage
+    echo "  --debug, -d"
+    printf "    Enable debug mode\n"
+    echo
+    
+    # :flag.usage
+    echo "  --no-logo"
+    printf "    Not print logo\n"
+    echo
+    
+    # :flag.usage
+    echo "  --run, -r"
+    printf "    Run scripn after building\n"
+    echo
+    
+    # :flag.usage
+    echo "  --sysinfo"
+    printf "    Print System info\n"
+    echo
+    # :command.usage_args
+    printf "Arguments:\n"
+    
+    # :argument.usage
+    echo "  SELECT"
+    printf "    Selecte some scripts\n"
+    echo
+
+    # :command.usage_examples
+    printf "Examples:\n"
+    
+    printf "  cli build\n"
+    printf "  cli build -d -r\n"
+    printf "  cli build \"vlc GUI\"\n"
+    printf "  cli build --sysinfo \"vlc GUI\"\n"
+    echo
+
+  fi
+}
+
+# :command.inspect_args
+inspect_args() {
+  readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
+  if (( ${#args[@]} )); then
+    echo args:
+    for k in "${sorted_keys[@]}"; do echo "- \${args[$k]} = ${args[$k]}"; done
+  else
+    echo args: none
+  fi
+
+  if (( ${#other_args[@]} )); then
+    echo
+    echo other_args:
+    echo "- \${other_args[*]} = ${other_args[*]}"
+    for i in "${!other_args[@]}"; do
+      echo "- \${other_args[$i]} = ${other_args[$i]}"
+    done
+  fi
+}
+
+# :command.command_functions
+# :command.function
+oh_my_linux_build_command() {
+  # :src/build_command.sh
+  case "${args[--debug]}" in
+        1) DEBUG=true ;;
+        *) DEBUG=$DEBUG ;;
+  esac
+
+  if [ "${args[--no-logo]}" != 1 ]; then
+    print_logo
+  fi
+  log_debug "DEBUG Mode!"
+
+  update_all_info;
+
+  if [ "${args[--sysinfo]}" = 1 ]; then
+    print_all_info
+  fi
+
+  select_scripts
+
+
+  topological_sort; 
+  build_script;
+
+  if [ "$DEBUG" = true ]; then
+    inspect_args
+  fi
+}
+
+# :command.parse_requirements
+parse_requirements() {
+  # :command.fixed_flag_filter
+  case "$1" in
+  --version | -v )
+    version_command
+    exit
+    ;;
+  
+  --help | -h )
+    long_usage=yes
+    oh_my_linux_usage
+    exit 1
+    ;;
+  
+  esac
+  # :command.environment_variables_filter
+  # :command.dependencies_filter
+  # :command.command_filter
+  action=$1
+  
+  case $action in
+  -* )
+    ;;
+  
+  build | b )
+    action="build"
+    shift
+    oh_my_linux_build_parse_requirements "$@"
+    shift $#
+    ;;    
+  
+  # :command.command_fallback
+  * )
+    oh_my_linux_usage
+    exit 1
+    ;;
+  
+  esac
+  # :command.required_args_filter
+  # :command.required_flags_filter
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+  
+    -* )
+      printf "invalid option: %s\n" "$key"
+      exit 1
+      ;;
+  
+    * )
+      # :command.parse_requirements_case
+      printf "invalid argument: %s\n" "$key"
+      exit 1
+      ;;
+  
+    esac
+  done
+  # :command.default_assignments
+  # :command.whitelist_filter
+}
+
+# :command.parse_requirements
+oh_my_linux_build_parse_requirements() {
+  # :command.fixed_flag_filter
+  case "$1" in
+  --version | -v )
+    version_command
+    exit
+    ;;
+  
+  --help | -h )
+    long_usage=yes
+    oh_my_linux_build_usage
+    exit 1
+    ;;
+  
+  esac
+  # :command.environment_variables_filter
+  # :command.dependencies_filter
+  # :command.command_filter
+  action="build"
+  # :command.required_args_filter
+  # :command.required_flags_filter
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+    # :flag.case
+    --debug | -d )
+      args[--debug]=1
+      shift
+      ;;
+  
+    # :flag.case
+    --no-logo )
+      args[--no-logo]=1
+      shift
+      ;;
+  
+    # :flag.case
+    --run | -r )
+      args[--run]=1
+      shift
+      ;;
+  
+    # :flag.case
+    --sysinfo )
+      args[--sysinfo]=1
+      shift
+      ;;
+  
+  
+    -* )
+      printf "invalid option: %s\n" "$key"
+      exit 1
+      ;;
+  
+    * )
+      # :command.parse_requirements_case
+      if [[ ! ${args[select]} ]]; then
+        args[select]=$1
+        shift
+      else
+        printf "invalid argument: %s\n" "$key"
+        exit 1
+      fi
+      ;;
+  
+    esac
+  done
+  # :command.default_assignments
+  # :command.whitelist_filter
+}
+
+# :command.initialize
+initialize() {
+  version="0.1.0"
+  long_usage=''
+
+  # if [ "$DEBUG" != true ]; then # TODO: fix it!
+  #   set -e  
+  # fi
+
+  detect_scripts_directories;
+
+}
+
+# :command.run
+run() {
+  declare -A args
+  declare -a other_args
+  parse_requirements "$@"
+
+  if [[ $action == "build" ]]; then
+    if [[ ${args[--help]} ]]; then
+      long_usage=yes
+      oh_my_linux_build_usage
+    else
+      oh_my_linux_build_command
+    fi
+  
+  elif [[ $action == "root" ]]; then
+    root_command
+  fi
+}
+
+
 if [ "${1}" != "--source-only" ]; then
-    main "${@}"
+    initialize
+    run "$@"
 fi
